[package]
name = "desktop-app"
version = "0.1.0"
description = "TabForge Multi-Tab Browser Recording Runtime"
authors = ["dsk-dev-ai"]
edition = "2021"

[lib]
name = "desktop_app_lib"
crate-type = [
    "staticlib",
    "cdylib",
    "rlib"
]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]

# ==============================
# TAURI
# ==============================

tauri = { version = "2", features= [] }

tauri-plugin-opener = "2"


# ==============================
# SERIALIZATION
# ==============================

serde = {
    version="1",
    features= ["derive"]
}

serde_json="1"


# ==============================
# ASYNC RUNTIME
# ==============================

tokio = {
    version="1",
    features= [
        "full"
    ]
}


# ==============================
# WEBSOCKET
# ==============================

tokio-tungstenite="0.24"

futures-util="0.3"


# ==============================
# RANDOM SESSION IDS
# ==============================

rand="0.8"


# ==============================
# FUTURE:
# FFMPEG + STREAM PIPELINES
# ==============================

bytes="1"

uuid= {
    version="1",
    features= [
        "v4"
    ]
}


# ==============================
# LOGGING
# ==============================

log="0.4"

env_logger="0.11"
